# Generated by Django 3.1.3 on 2020-11-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_linksmenu_sameproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='город')),
                ('phone', models.CharField(max_length=64, verbose_name='телефон')),
                ('email', models.CharField(max_length=64, verbose_name='email')),
                ('address', models.CharField(max_length=64, verbose_name='адрес')),
            ],
        ),
        migrations.DeleteModel(
            name='SameProducts',
        ),
    ]
